config/routes.rb
Bookmarks::Application.routes.draw do
  get "dashboard/index"
  get "dashboard/users_index"
  get "dashboard/users_show"

  resources :administrators do
   get 'logout' , :on => :collection
  end

  resources :bookmarks

  resources :home do
  get 'view_all' , :on => :collection
  get 'logout' , :on => :collection
  get 'login' , :on => :collection
end
   
 
resources :users 

   root :to => "home#index"

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
 
 belongs_to :user
 validates :title , :presence => true
 validates :description , :length => {:maximum => 20}
validates :user_id , :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :bookmarks , :dependent => :destroy

  validates :name , :presence => true
 validates :emailid , :presence => true
validates :password , :presence => true
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
 
  #before_filter :check_session 
 
  def index
   @administrators = Administrator.all
  end

  def new
    @administrator = Administrator.new
  end

  def show
  end

  def create
    @administrator = Administrator.new(params[:administrator])
     @admin = Administrator.find_all_by_username(@administrator.username)
     if(!@admin.blank? && @admin.first.password.eql?(@administrator.password))
     session[:admin] = @admin.first.id
     flash[:notice] = "Logged in Successfully"
     redirect_to dashboard_index_path
     else
    flash[:error] = "Failed to login"
    redirect_to administrators_path
   end
end

  def edit

  end
  def logout 
puts"11111111111111111111111111111!"  
   session[:admin] = nil if session[:admin]   

   redirect_to administrators_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def check_session_user
        if session[:user].nil?
      flash[:error] = "You are not authenticated"
     redirect_to home_index_path
    end
 end
 
 def check_session_admin
    if session[:admin].nil?
      flash[:error] = "You are not authenticated"
     redirect_to dashboard_index_path
    end
 end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
 
  before_filter :check_session_user

 def index
  @bookmarks = Bookmark.paginate(:page => params[:page], :per_page => 4)
  
  end

def new 
 @bookmark = Bookmark.new
end

def create
 @user = User.find(session[:user])
 @bookmark=Bookmark.new(:title => params[:bookmark][:title],:description => params[:bookmark][:description],:user_id => @user.id)
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to users_path, :notice => 'Bookmark was successfully created.' }
       else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
     end
  end
end

def show
  @bookmark = Bookmark.find(params[:id])
end

def edit
 @bookmark = Bookmark.find(params[:id])
end
def update
 @bookmark = Bookmark.find(params[:id])
 respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to(users_path, :notice => 'Bookmark was successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
end

def destroy
  @bookmark = Bookmark.find(params[:id])
     @bookmark.destroy
 redirect_to users_path
end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
before_filter :check_session_admin

  def index
  end
  
 def users_index
   @users = User.all
 end
 def users_show
  @user = User.find(params[:id])
 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 #before_filter :check_session

 def index
   @total_bookmarks = Bookmark.paginate(:page => params[:page], :per_page => 4)
   @users = User.limit(3)
  end
 def create
   @user = User.new(params[:user])
   @user1 = User.find_all_by_emailid(@user.emailid)
   if(!@user1.blank? && @user1.first.password.eql?(@user.password))
    session[:user] = @user1.first.id
    flash[:notice] = "Logged in Successfully"
    redirect_to users_path
   else
    flash[:error] = "Failed to login"
    redirect_to home_index_path
   end
  end 
 def show
   @user = User.find(params[:id])
    end
  def view_all
   @users=User.all
  end
  def logout
   session[:user] = nil if session[:user]
   flash[:notice] = "Logged out Successfully"
     redirect_to home_index_path
  end
  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
#before_filter :check_session_user
 def index
   @user = User.find(session[:user])
  @bookmarks = Bookmark.where(:user_id => @user.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  def new
   @user = User.new
  end

  def create
    if (params[:user][:password] == params[:confirmpassword]) 

         @user=User.new(:name => params[:user][:name],:emailid => params[:user][:emailid],:password => params[:user][:password]) 

       respond_to do |format|
         if @user.save
            format.html { redirect_to users_path }
     flash[:notice] = "User Saved Successfully"
        else
            format.html{render :action => "new"}
      flash[:error] = "User failed to Save"
format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
       end
    end
   else
       redirect_to users_path
  end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit

    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'User successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
  end

  def destroy
   @user = User.find(params[:id])
    @user.destroy
 redirect_to users_path
  end



end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrators/edit.html.erb
<h1>Administrators#edit</h1>
<p>Find me in app/views/administrators/edit.html.erb</p>

app/views/administrators/index.html.erb
<%= form_for(:administrator) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %> </br>
    <%= f.label :password %>
  <%= f.password_field :password %> </br>
    <%= f.submit  %> </br>
<% end %>

app/views/administrators/new.html.erb
<div align="center">

<%= form_for(@administrator) do |f|%>
  <%= f.label :Username %>
  <%= f.text_field :username %><br/>
<%= f.label :Password  %>
  <%= f.password_field :password %><br />
  <%= f.submit "Login" %><br /></br />
<% end %>

</div>

app/views/administrators/show.html.erb
<h1>Administrators#show</h1>
<p>Find me in app/views/administrators/show.html.erb</p>

app/views/bookmarks/_form.html.erb
<% if @bookmark.errors.any? %>
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

    <ul>
    <% @bookmark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

<% end %>

<%= form_for(@bookmark) do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %> </br>
  <%= f.label :Description %>
  <%= f.text_field :description %> </br>
    <%= f.submit "submit"%> </br>
<% end %>

app/views/bookmarks/edit.html.erb
<%= render "form"%>

app/views/bookmarks/index.html.erb
<%= render 'home/admin' %>
<h1>Listing Bookmarks</h1>
<%= will_paginate %>
<table >
  

<% @bookmarks.each do |bookmarks| %>
  <tr>
    <td><h4>Name</h4></td>
    <td><%= bookmarks.user_id %></td></tr>
<tr>
<td><h4>Title</h4></td>
    <td><%= link_to bookmarks.title , bookmarks.title , :target => :_blank %></td></tr>
<tr><td><h4>Description</h4></td>
    <td><%= bookmarks.description %></td></tr>
<tr>
    <td><%= link_to 'Show', bookmarks %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmarks) %></td>
    <td><%= link_to 'Destroy', bookmarks, :confirm => 'Are you sure?', :method => :delete %></td></tr>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate %>
<br />
<%= link_to 'New Update', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<%= render 'form' %>

app/views/bookmarks/show.html.erb
<b>UserId : </b>
 <%= @bookmark.user_id %><br />
<b>Title : </b>
 <%= @bookmark.title %><br />
<b>Description : </b>
 <%= @bookmark.description %><br />

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', users_path %>

app/views/dashboard/index.html.erb
<%= link_to 'Logout' , logout_administrators_path %>
<%= link_to 'Users' , dashboard_users_index_path%>

app/views/dashboard/users_index.html.erb
<% @users.each do |u| %>
<%= link_to u.name , dashboard_users_show_path(:id => u.id) %><br/>
<% end %>

app/views/dashboard/users_show.html.erb
<b>UserName : </b>
 <%= @user.name %><br />
<b>EmailId : </b>
 <%= @user.emailid %><br />

<b>Bookmarks</b><br />
<% @user.bookmarks.each do |b| %>
<%= b.title %><br />
<% end %>

<%= link_to 'Back', dashboard_users_index_path %>

app/views/home/_admin.html.erb
<%= link_to 'Logout' , logout_home_index_path %>
<%= link_to 'Users' , users_path%>

app/views/home/_form.html.erb
<%= form_for(:user) do |f|%>
<i style="color:green">Already A User  :</i>  <br />  
<%= f.label :email %>
  <%= f.text_field :emailid %><br />
<%= f.label :Password  %>
  <%= f.password_field :password %><br />
  <%= f.submit "Login" %>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<body>
<%= stylesheet_link_tag "public/new.css" %>

<div id='center'>
  <div id='center-left'>
<%= link_to 'Already A User?,Click Here..' , login_home_index_path %> &nbsp &nbsp &nbsp &nbsp &nbsp
<%= link_to 'Admin..' , administrators_path %>  
    <%#= render 'home/form' %><br/><br/><br/><br/>
<%= will_paginate @total_bookmarks %><br />
<i style="font-size:20px">Users Bookmarks</i><br />
<% @total_bookmarks.each do |bookmarks| %>
<%= link_to bookmarks.title , bookmarks.title, :target => :_blank%><br />
<% end %><br/>
<%= will_paginate @total_bookmarks %>
  </div>
<div id='center-right'>
  
 <i style="font-size:20px">Do u Want To Register</i>
 <%= link_to "Register Now",new_user_path %> <br/><br/><br/>
<i style="font-size:20px">Users </i><br />
<% @users.each do |users| %>
<%= link_to users.name , home_path(:id => users.id) %><br />
<% end %>
</br></br>
<%= link_to 'viewall' , view_all_home_index_path%>
  </div>
 

</body>
</html>

app/views/home/login.html.erb
<%= form_for(:user , :url => {:controller => "home" , :action => "create"}) do |f|%>

<%= f.label :email %>
  <%= f.text_field :emailid %><br />
<%= f.label :Password  %>
  <%= f.password_field :password %><br />
  <%= f.submit "Login" %>
<% end %>

app/views/home/show.html.erb
<b>UserName : </b>
 <%= @user.name %><br />
<b>EmailId : </b>
 <%= @user.emailid %><br />

<b>Bookmarks</b><br />
<% @user.bookmarks.each do |b| %>
<%= b.title %><br />
<% end %>

<%= link_to 'Back', view_all_home_index_path %>

app/views/home/view_all.html.erb
<b>View All Users : </b><br/><br />
<% @users.each do |b| %>
<%= link_to b.name , home_path(:id => b.id) %><br />
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<% flash.each do |key, msg| %>
    <%=content_tag :div, msg, :id =>"flash_#{key}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/new.html.erb
<html>
<body>
<%= stylesheet_link_tag 'new.css' %>
<div class='container'>
</div>
<div class='container'>
</div> 
<div id='center'>
  <div id='center-left'>
    <% yield %>
  </div>
  <div id='center-right'>
  
 <i style="font-size:20px">Do u Want To Register</i>
 <%= link_to "Register Now",new_user_path %> 

</div></br></br>
<div align="right">
<i style="font-size:20px">Users Bookmarks</i>
<% @total_bookmarks.each do |bookmarks| %>
<%= link_to bookmarks.title , bookmarks.title, :target => :_blank%>
<% end %>
</div>

  </div>
</div> 
</body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

<% end %>


<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> </br>
  <%= f.label :email %>
  <%= f.text_field :emailid %> </br>
  <%= f.label :password %>
  <%= f.password_field :password %> </br>
  confirmpassword
  <%= password_field_tag :confirmpassword %>  
  <%= f.submit "submit"%> </br>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'home/admin' %>
<h1>Welcome to your profile</h1>
<table >
<tr>
    <td><h4>Name</h4></td>
    <td><%= @user.name %></td></tr><tr>
     <td><%= link_to 'Edit', edit_user_path(@user.id) %></td>
    <td><%= link_to 'Destroy', users_path, :confirm => 'Are you sure?', :method => :delete %></td></tr>
  </tr>
  
<% @bookmarks.each do |books| %>
 <tr>
   <td><span>Title :</span></td>
   <td><%= link_to books.title , books.title ,:target=>:_blank %></td></tr></br>    
   <td><span>Description :</span></td>
   <td><%=  books.description %></td></tr></br>

<tr>
   <td><%= link_to 'Show', books %></td>
   <td><%= link_to 'Edit', edit_bookmark_path(books) %></td>
   <td><%= link_to 'Destroy', books, :confirm => 'Are you sure?', :method => :delete %></td></tr></br>
 </tr>
<% end %>

  


</table>

<br />

<br />

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<b>Name : </b>
 <%= @user.name %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>